// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Keep this Prisma config file type-checkable even if Prisma's helper types
// (e.g. `prisma/config`) aren't resolvable in the current TS setup.
const config = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
} satisfies {
  schema: string;
  migrations: { path: string };
  datasource: { url: string | undefined };
};

export default config;
